# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(db_index=True, max_length=128)),
                ("role", models.CharField(max_length=16)),
                ("content", models.TextField()),
                ("external_id", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent message",
                "verbose_name_plural": "Agent messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="agentmessage",
            index=models.Index(
                fields=["user", "thread_id", "created_at"],
                name="ai_agent_ag_user_id_8c1e4a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentmessage",
            constraint=models.UniqueConstraint(
                fields=("thread_id", "external_id"),
                name="ai_agent_message_thread_external_id",
            ),
        ),
    ]
